//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EURIS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listino
    {
        public Listino()
        {
            this.Prodotti_x_listino = new HashSet<Prodotti_x_listino>();
        }
    
        public int id { get; set; }
        public string codice { get; set; }
        public string descrizione { get; set; }
    
        public virtual ICollection<Prodotti_x_listino> Prodotti_x_listino { get; set; }
    }
}
